### ISSUE TITLE
undefined is not an object (evaluating 'window.emitter.emit') in Andriod

### ISSUE THREAD

**Issue by CacaoRick** [expo/expo-pixi#10]
* expo 25.0.0
* expo-pixi 0.2.2
* Android 7.1.1
* iOS is OK

```
  "dependencies": {
    "expo": "^25.0.0",
    "expo-pixi": "0.2.2",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz"
  },
```

Also happen when run `examples/basic` with expo-pixi 0.2.2
or just `import ExpoPixi from 'expo-pixi';` in other project

![https://i.imgur.com/p4I8MEP.jpg](https://i.imgur.com/p4I8MEP.jpg)

**Comment by EvanBacon** [comment]
odd will take a look when I get a second

**Comment by Shpadoinkle** [comment]
having same issue here. 

Running exact same versions as OP,  works fine on iOS, crashes on android.

**Comment by maxusr** [comment]
May be the problem come from @expo/browser-polyfill.
in 0.0.0-alpha.3 in resize.js file we have this code 
`window.emitter.emit('resize');`
but in 0.0.0-alpha.5 we have this code
`if (window.emitter && window.emitter.emit) {
        window.emitter.emit('resize');
      }`
so maybe this simple verification make all this problem. I have the same issue with Android bug but ok in iOS. I will try tomorrow and report if all is gut.

**Comment by EvanBacon** [comment]
This was due to image rotation, @maxusr is correct, the fix in browser-polyfill corrected this. closing
