### ISSUE TITLE
Is this possible to undo a drawing in ExpoPixi.Sketch?

### ISSUE THREAD

**Issue by jarvisluong** [expo/expo-pixi#11]
I want to implement a functionality that works similar to Snapchat and I wonder is it possible to undo a drawing using this library?

**Comment by EvanBacon** [comment]
That's a dope idea will add when I get a second or you could PR!
* make an undo function
* pop this array https://github.com/expo/expo-pixi/blob/a3254a7f6ccfbf700c6d49248414dbf71a8592c0/lib/components/Sketch.js#L111
* update the render: https://github.com/expo/expo-pixi/blob/a3254a7f6ccfbf700c6d49248414dbf71a8592c0/lib/components/Sketch.js#L140

**Comment by jarvisluong** [comment]
hmm I popped that array and call update but no changes happens when I call the undo function

this is what I'm doing:

`undoLastLine() {
    if (!this.renderer || this.lines.length === 0) {
      return;
    }
    this.lines.pop();
    this.renderer._update();
  }`

**Comment by EvanBacon** [comment]
You will also need to remove the line graphic from the stage:
```js
const child = this.lines.pop();
this.state.removeChild(child);
```

**Comment by jarvisluong** [comment]
currently this is the function, however, it undo the line before the last line and if I keeps calling this undo function, it delete the lines before the last line in the correct chronological order, I assume the last line I draw is not in thie.lines?
```javascript
undoLastLine() {
    if (!this.renderer || this.lines.length === 0) {
      return;
    }
    const lastChild = this.lines.pop();
    this.stage.removeChild(lastChild);
    this.renderer._update();
  }
```

**Comment by obiwankenoobi** [comment]
Any chance for explanation on how this work? I am also facing the same problem and need to undo a lines.
