### ISSUE TITLE
Unable to Use ExpoPixi in VS Code

### ISSUE THREAD

**Issue by vokecodes** [expo/expo-pixi#124]
After installation with yarn add, I get below error in VS Code

module "c:/Users/USER/Documents/Kiwi/node_modules/expo-pixi/lib/index"
'ExpoPixi' is declared but its value is never read.ts(6133)
Could not find a declaration file for module 'expo-pixi'. 'c:/Users/USER/Documents/Kiwi/node_modules/expo-pixi/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/expo-pixi` if it exists or add a new declaration (.d.ts) file containing `declare module 'expo-pixi';`ts(7016)

```
"dependencies": {
    "expo-pixi": "^1.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
}
```

**Comment by RayBans2111** [comment]
hey voke, I ran into this about half an hour ago when I installed expo-pixi. Create a .ts file that simple says 'declare module expo-pixi.' and this should go away.
