### ISSUE TITLE
Cannot read property of '0' in Expo-pixi

### ISSUE THREAD

**Issue by abrarum** [expo/expo-pixi#19]
I hope it'll benefit others too.

I've a sample code adapted from https://github.com/expo/expo-pixi/blob/master/examples/filter-image/App.js,

I tried running this code on Snack and its working but as soon as I try to run it in my remote environment, it isn't working. It gives an error: "Cannot read property '0' of undefined".

I tried to debug the problem by trial and error and found that this something related to this chunk:

```
<ExpoPixi.FilterImage
            source={require('./assets/kylie.png')}
            resizeMode={'cover'}
            style={styles.image}
            filters={filter}
 />
```

When every I try to add the styles esp. the width and height, the red box popups every time giving above error.
![image](https://user-images.githubusercontent.com/7055212/39941549-59e7a108-5576-11e8-8b50-a492038b311a.png)

**Comment by abrarum** [comment]
Any temporary solution for that or any workaround?

**Comment by abrarum** [comment]
Hi. I tried this. It worked the first time but then the same error is appearing again. :(

**Comment by abrarum** [comment]
Now, I tried to run this example: https://snack.expo.io/@abraracs/gl-expo-example adapted from gl-react docs and this is showing the same error of '0' undefined. I'm using gl-react and gl-react-expo example.

**Comment by abrarum** [comment]
Any update?

**Comment by EvanBacon** [comment]
You will need to provide more information on the issue, things like your specific device and OS. I can't help if I can't replicate the error

**Comment by semiautomatix** [comment]
Yup, simple example:

`import React, { Component } from 'react';
import { View, ScrollView, Text, KeyboardAvoidingView, ToolbarAndroid } from 'react-native';
import { connect } from 'react-redux';
import Expo from 'expo';
import ExpoPixi from 'expo-pixi';
// Add Actions - replace 'Your' with whatever your reducer is called :)
// import YourActions from '../Redux/YourRedux'

// Styles
import styles from './Styles/WaybillScreenStyle';

const color = 0x0000ff;
const width = 5;
const alpha = 0.5;

class WaybillScreen extends Component {
	render () {
		return (
				<View>
					<ToolbarAndroid
						style={{
							height: 45,
							paddingTop: 20
						}}
						title="Waybill 123456"
					/>				
          <ExpoPixi.Sketch
						strokeColor={color}
						strokeWidth={width}
						strokeAlpha={alpha}
						style={{height:100,width:100}}
					/>
			</View>
		);
	}
}

const mapStateToProps = state => ({
});

const mapDispatchToProps = dispatch => ({
});

export default connect(mapStateToProps, mapDispatchToProps)(WaybillScreen);
`
And I'm receiving the above error.

**Comment by semiautomatix** [comment]
Ok, I overlooked 

> This lib uses @expo/browser-polyfill please take a look at this issue with v26. You will need to run rm -rf > node_modules/gl-matrix/.babelrc after running yarn or npm install

Seems to be working now.

**Comment by EvanBacon** [comment]
Just going to assume this is android then...

**Comment by EvanBacon** [comment]
This runs the same on both iOS (iPhone 7+) and Android (Pixel 2) https://snack.expo.io/@bacon/pixi-sketch

**Comment by pzupan** [comment]
The culprit seems to be remote debugging. "the current implementation of remote debugging in React Native runs in a different JavaScript context than the one on your device so this isn’t trivially fixable."  https://forums.expo.io/t/missing-gl-interfaces-make-glview-fail/1723/11

**Comment by EvanBacon** [comment]
Closing, you cannot remote debug or use EXGL in the simulator
