### ISSUE TITLE
How do I save filtered images...?

### ISSUE THREAD

**Issue by SeongmanMannKim** [expo/expo-pixi#23]
Literally, how do I save those filtered images...?
Tried finding the source, no luck yet.
If any helpful resources, please redirect me.

Thank you,

**Comment by EvanBacon** [comment]
You could screen shot the view using [`Expo.takeSnapshotAsync(view, options)`](https://docs.expo.io/versions/latest/sdk/take-snapshot-async#__next). Remember to turn the quality up to `1.0`
