### ISSUE TITLE
First line drawn with ExpoPixi.Sketch is not captured?

### ISSUE THREAD

**Issue by jhowarth15** [expo/expo-pixi#25]
Hi everyone! Great library that solves a real pain point - great stuff!

I almost have a nice little signature capture working.. however the first line drawn is not recorded in this.sketch.lines even though it shows in the Sketch component. The onChange function is not even fired.

I'm re-using your code @EvanBacon from your very useful [article](https://blog.expo.io/drawing-signatures-with-expo-25d1629ca1ac).

I would appreciate any help from anyone who has faced the same issue!

This is my component: 
```
import Expo from 'expo';
import React from 'react';
import { Image, View, Text, StyleSheet, TouchableOpacity } from 'react-native';
import ExpoPixi from 'expo-pixi'
import config from '../config';

export default class SignatureBox extends React.Component {

	constructor(props) {
		super(props);

		this.state = {
		};
	}

	onChange = () => {
		  for (let line of this.sketch.lines) {
		    console.log(line.points)
		  }
	}

	render() {

		return (

			<View style={styles.container}>
				<ExpoPixi.Sketch
				  ref={ref => (this.sketch = ref)}
				  style={styles.sketch}
				  strokeColor={'black'}
				  strokeWidth={5}
				  strokeAlpha={1}
				  onChange={this.onChange}
				/>
			</View>

		);
	}
}

```

**Comment by EvanBacon** [comment]
I'll take a look at it today!

**Comment by jhowarth15** [comment]
Awesome, thanks Evan

**Comment by jhowarth15** [comment]
If you provide the initialLines prop with at least one line in the array, the first user draw is captured.

So a (hacky) fix to the problem is to provide an initial line which is offscreen 😄 

```
export default class SignatureBox extends React.Component {

	constructor(props) {
		super(props);

		this.state = {
			lines: [
				{
					points: [{ x: 1000, y: 80 }, { x: 1200, y: 80 }],
					color: 0,
					alpha: 1,
					width: 5,
				},
			],
		};
	}

	onChange = async () => {


		for (let line of this.sketch.lines) {
			console.log(line.points)
		}

	}


	render() {


		return (

			<View style={styles.container}>


					<ExpoPixi.Sketch
						ref={ref => (this.sketch = ref)}
						strokeColor={0x000000}
						strokeWidth={5}
						strokeAlpha={1}
						onChange={this.onChange}
						style={styles.sigNotReady}
						initialLines={this.state.lines}
					/>



			</View>

		);
	}
}
```

**Comment by jhowarth15** [comment]
@EvanBacon I incorrectly diagnosed the issue. The first line is captured, but this.sketch.lines in the onChange function is always one line behind.

So when the first line is drawn this.sketch.lines is [], then after the second line is drawn then this.sketch.lines contains the first line. Third line drawn and it contains the first two, and so on.

This means that the actual problem is that I lose the last line that the user inputs.. could this be an async issue on my part?

**Comment by jhowarth15** [comment]
I have a fix - this.sketch.points contains the points of the last line. So you can append this to this.sketch.lines to get all the lines that the user inputs, including the last line. 😸

**Comment by EvanBacon** [comment]
Will look into a long term solution. Until then I would recommend using the new `Signature` component.

**Comment by isthaison** [comment]
how to use  Signature  with backgroud image? @EvanBacon

**Comment by isthaison** [comment]
![20180422_002145](https://user-images.githubusercontent.com/22739578/48831030-8e26db80-eda8-11e8-960b-a47306c209e4.jpg)
sample

**Comment by 1k2k** [comment]
@EvanBacon which new Signature component would can i use in Expo,

**Comment by JasonMize** [comment]
@EvanBacon This still seems to be an issue.  The reason I'm using sketch instead of signature is because I need it to be a transparent background.  @isthaison showed this should be possible.  How?
