### ISSUE TITLE
Cannot debug when Expo.Pixi.Sketch component is mounted

### ISSUE THREAD

**Issue by mike-oodle** [expo/expo-pixi#28]
Hi, I'm looking for some help.  I am using this in a CRNA app with Expo.  Whenever I enable remote debugging when the `<Sketch/>` component is mounted, I get the following error:

```
Cannot read property 'x' of undefined

Object.onPanResponderMove
Sketch.js:86:15
```

I have so far been able to kind-of-sort-of work around this using some logging to figure out what's happening but my app has since gotten a little more complicated and it's no longer time-efficient to use logging.

I wanted to see if this is a known issue and whether there's a fix in the pipeline or a known fix?  I'd be happy to submit a PR but I wanted to get some understanding of whether this is a fix that needs to happen within this project or the Pixi.js project before I started trying to get something working.

**Comment by EvanBacon** [comment]
#19 cannot use remote debugging in the simulator. Remote debugging runs a copy of your js bundle in the browser. This is too heavy an operation for EXGL.

**Comment by mike-oodle** [comment]
Thanks, Evan.  That saves me some time trying to figure out a work around.
