### ISSUE TITLE
Draw on picture

### ISSUE THREAD

**Issue by mlecoq** [expo/expo-pixi#59]
Hi,

I would like to use ExpoPixi.Sketch component to be able to draw on existing picture. I don't figure out how to passe an uri to the component (like in FilterImage case) 

Maybe through onReady() ? Is it possible ?

Thanks a lot

**Comment by DEllement** [comment]
so the way i make this possible, is to get the reference of the Sketch stage & renderer instance
you can then add your sprite or graphics to the stage but dont forget to call renderer._update();

` <ExpoPixi.Sketch ref={ref => (this.sketch = ref)} ... />`

**Comment by leonyhenn** [comment]
@DEllement  Can you post an example? sprite always gives me back "Unexpected Url"

**Comment by DEllement** [comment]
ok, it might be the way you load your sprite then, depending on which version you are using it might be more or less straight forward, here how i load my sprite:

`const asset = await AssetUtils.resolveAsync(FileSystem.documentDirectory+"medias/"+this.selectedResource.id+".jpg");
        var background = PIXI.Sprite.from(PIXI.Texture.from(new HTMLImageElement(asset)));
        background.width = 1000;
        background.height = 1000;

        this.pixiStage.addChild(background);
        this.pixiRenderer._update();`

**Comment by leonyhenn** [comment]
@DEllement  uh this is very interesting. Due to recent(1.0.0) expo-pixi has some referece errors, I was using Nov 19, 2018 version commit of this repository. You are right, the sprite on this version do not load this way. I ll dig deeper to see what is going on, thanks for fast reply!

**Comment by leonyhenn** [comment]
@DEllement btw, did u encounter any reference issue with the latest version of expo-pixi? which version did you use?

**Comment by DEllement** [comment]
yes with version 1.0.0 there is some issues, someone posted a pull request, i tried applying the patch without success, this is why i use the old implementation of spriteAsync in my code, but its working in my case, and the definition file for typescript seam not in sync as well.

**Comment by mlecoq** [comment]
I will try this, thanks a lot ! I owe you a beer ;)

**Comment by leonyhenn** [comment]
@DEllement I tried a dozens of times, still gives me Unexpected url. I was using an Expo filesystem url like this: file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540leonyhenn%252Ffront-by-component/ImagePicker/ce4e215f-0078-4087-b028-7bfa2ab2f594.jpg 

I even tried online url from the snack, 'http://i.imgur.com/uwrbErh.png' but still no luck

Can you elaborate a little more on how to load sprite here?

**Comment by leonyhenn** [comment]
@DEllement My version was the one commited on Nov 19, 2018, you can view it on the repo history

**Comment by DEllement** [comment]
ok ill try,

```
// we need to load the asset itself
const asset = await AssetUtils.resolveAsync(FileSystem.documentDirectory+"medias/"+this.selectedResource.id+".jpg");
//try tracing the asset to see if you have a file object with the correct file path
console.log(asset);
//then we need to create en HTMLImageElement, this is the catch part, as youll need some sort of dom polyfill to make it work, im using the @expo/browser-polyfill, dont forget to install it
var img = new HTMLImageElement(asset)
//we create a PIXI.Texture using the img
var tex = PIXI.Texture.from( img)
//And the sprite using the texture
var sprite = PIXI.Sprite.from(txt)

```

from there you should have your sprite, now it just a matter of adding it to the stage, and force render if required by the renderer implementation.

**Comment by leonyhenn** [comment]
kk, i m gonna try this one. Thanks for being so patient!

**Comment by leonyhenn** [comment]
@DEllement  Nah, no luck, still getting unexpected url. Just contact repo owner, he said he ll pulish 1.0.1 for bug fix.

**Comment by DEllement** [comment]
can you show me the code?

**Comment by leonyhenn** [comment]
sure!
```javascript
import Expo from 'expo';
//This pixi version is a copy of Nov19_2018 commit of pixi
import * as ExpoPixi from '../components/Nov19_2018Pixi/ExpoPixi.js';
import React, { Component } from 'react';
import { Image, Button, Platform, AppState, StyleSheet, Text, View } from 'react-native';
import AssetUtils from 'expo-asset-utils';
import {FileSystem} from "expo";
//Official Modules
import { height, 
         width } from '../utility/Util.js';

const isAndroid = Platform.OS === 'android';
function uuidv4() {
  //https://stackoverflow.com/a/2117523/4047926
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    var r = (Math.random() * 16) | 0,
      v = c == 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

export default class App extends Component {
  constructor(props){
    super(props)
    this.state = {
      image: null,
      strokeColor: Math.random() * 0xffffff,
      strokeWidth: Math.random() * 30 + 10,
      lines: [
        {
          points: [{ x: 300, y: 300 }, { x: 600, y: 300 }, { x: 450, y: 600 }, { x: 300, y: 300 }],
          color: 0xff00ff,
          alpha: 1,
          width: 10,
        },
      ],
      appState: AppState.currentState,
      image_pos:{
        "height": 0,
        "width": 0,
        "x": 0,
        "y": 0,
      }
    };

    this.add=this.add.bind(this)
  }
  

  handleAppStateChangeAsync = nextAppState => {
    if (this.state.appState.match(/inactive|background/) && nextAppState === 'active') {
      if (isAndroid && this.sketch) {
        this.setState({ appState: nextAppState, id: uuidv4(), lines: this.sketch.lines });
        return;
      }
    }
    this.setState({ appState: nextAppState });
  };

  async add(){
    // we need to load the asset itself
  const asset = await AssetUtils.resolveAsync("file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540leonyhenn%252Ffront-by-component/ImagePicker/ce4e215f-0078-4087-b028-7bfa2ab2f594.jpg");
  //try tracing the asset to see if you have a file object with the correct file path
  console.log("asset",asset);
  //then we need to create a HTMLImageElement, this is the catch part, as youll need some sort of dom polyfill to make it work, im using the @expo/browser-polyfill, dont forget to install it
  var img = new HTMLImageElement(asset)
  //we create a PIXI.Texture using the img
  var tex = PIXI.Texture.from( img)
  //And the sprite using the texture
  var sprite = PIXI.Sprite.from(txt)
    this.sketch.addChild(sprite);
    this.sketch.renderer._update()
  }

  componentDidMount() {
    AppState.addEventListener('change', this.handleAppStateChangeAsync);
  }

  componentWillUnmount() {
    AppState.removeEventListener('change', this.handleAppStateChangeAsync);
  }

  onChangeAsync = async () => {
    const { uri } = await this.sketch.takeSnapshotAsync();

    this.setState({
      image: { uri },
      strokeWidth: Math.random() * 30 + 10,
      strokeColor: Math.random() * 0xffffff,
    });
  };

  onReady = () => {
    console.log('ready!');
  };

  render() {
    console.log(FileSystem.documentDirectory)
    return (
        <View style={styles.container}>
          <ExpoPixi.Sketch
            ref={ref => (this.sketch = ref)}
            style={[styles.sketch,{
              height: 300, 
              width:300,
            }]}
            strokeColor={this.state.strokeColor}
            strokeWidth={this.state.strokeWidth}
            strokeAlpha={1}
            onChange={this.onChangeAsync}
            onReady={this.onReady}
            initialLines={this.state.lines}
          />
        
        <Button
          color={'blue'}
          title="undo"
          style={styles.button}
          onPress={() => {
            this.sketch.undo();
          }}
        />
        <Button
          color={'blue'}
          title="add"
          style={styles.button}
          onPress={this.add}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems:'center',
    justifyContent:'center'


  },
  sketch: {
    flex: 1,
    borderWidth:1
  },
  sketchContainer: {
    height: height - 30,
    width:width,
  },
  image: {
    flex: 1,
  },
  imageContainer: {
    
    borderTopWidth: 4,
    borderTopColor: '#E44262',
  },
  label: {
    width: '100%',
    padding: 5,
    alignItems: 'center',
  },
  button: {
    // position: 'absolute',
    // bottom: 8,
    // left: 8,
    zIndex: 1,
    padding: 12,
    minWidth: 56,
    minHeight: 48,
  },
});

```

**Comment by DEllement** [comment]
ok i see, this is not guaranteed that your url point to an actual picture file, 

can you use the FileSystem helper like:
`Expo.FileSystem.documentDirectory`
or
`Expo.FileSystem.cacheDirectory`

also , where does that picture came from? did you downloaded it at first?
Here is an example on how to download a file to your document or cache folder:

```
var remoteFileUrl = "https://.....PUT A PICTURE URL HERE....."
var filename = "localfilename.png";
//Download File
        var folderInfo = await FileSystem.getInfoAsync(FileSystem.documentDirectory+"somefolder");
        if (!folderInfo.exists)
            await FileSystem.makeDirectoryAsync(FileSystem.documentDirectory+"somefolder");

      

            FileSystem.downloadAsync(remoteFileUrl, FileSystem.documentDirectory + "somefolder/" +filename)
                .then( res=>{console.log(res)})
                .catch(err=>console.warn(err));
        

```
you should be able to load the asset using

`const asset = await AssetUtils.resolveAsync(FileSystem.documentDirectory+"somefolder/"+filename);`


also, not sure about that, but you should add the sprite to the stage of the sketch component

`this.sketch.addChild(sprite); =>  this.sketch.stage.addChild(sprite);`

**Comment by leonyhenn** [comment]
@DEllement well, the fiile url is a part of workflow of my app, user pick an image from imagePicker, then annotate it. I doubt if the file exists at first, but below are the experiment that I did, and you can reproduce the same result:
Using the expo ImagePicker, pick an image, record the url; then remove the ImagePicker, add an <Image /> component with source url pointed to the recorded url, and the image will be displayed.

That's why I believed the url works, you can try to reproduce it.

The picture comes from my filesystem, I downloaded and saved it, it can be displayed with <Image/> component.  
ImagePicker only returns above url, so I cannot get a url in the filesystem, that's why I did not use Filesystem.documentDirectory or cacheDirectory.

again, Thanks for being so patient and helpful!

**Comment by leonyhenn** [comment]
For ImagePicker, below is the example code, you can try it on your machine to get the url:
```javascript
import React from 'react';
import { Button, Image, View } from 'react-native';
import { ImagePicker } from 'expo';

export default class ImagePickerExample extends React.Component {
  state = {
    image: null,
  };

  render() {
    let { image } = this.state;

    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Button
          title="Pick an image from camera roll"
          onPress={this._pickImage}
        />
        {image &&
          <Image source={{ uri: image }} style={{ width: 200, height: 200 }} />}
      </View>
    );
  }

  _pickImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      allowsEditing: true,
      aspect: [4, 3],
    });

    console.log(result);

    if (!result.cancelled) {
      this.setState({ image: result.uri });
    }
  };
}
```

**Comment by leonyhenn** [comment]
also, if u check the url returned from ImagePicker with FileSystem.getInfoAsync after remove ImagePicker and reload, it will tell you the file exist.

**Comment by DEllement** [comment]
ok,
can you trace every instance of the add() method and put them into try catch to handle any silent errors?

we need to know where it fail exactly

**Comment by leonyhenn** [comment]
doing it right now.

**Comment by leonyhenn** [comment]
same message.
![image](https://user-images.githubusercontent.com/16746119/52672888-17a00280-2eed-11e9-9064-17100fdbb37b.png)

**Comment by leonyhenn** [comment]
Can you try your solution on my code? the one goes FileSystem.documentDirectory+"medias/"+this.selectedResource.id+".jpg"?

**Comment by leonyhenn** [comment]
I dont know where to get the this.selectedResource.id, I can only get above url from ImagePicker, so I cant try it on my side

**Comment by DEllement** [comment]
Ok ill have to check a bit later though, but to me it really look like that it cannot find the file,
technically you should use the same image uri provided by the image picker and not a hardcoded path

also i didnt see the poly import in your code:
`import '@expo/browser-polyfill';`

so look, try making sure you got the handle on the file, ill see what i can do later.

**Comment by leonyhenn** [comment]
kk, i ll add an imagepicker to make sure image get picked first

**Comment by DEllement** [comment]
Ok, so i noticed that my solution doesn't work on android but in iOS yes, i do have to make it work, so ill work on that tonight and post the solution here

**Comment by leonyhenn** [comment]
oh I tested on android. Looking forward to ur solution tmr

**Comment by DEllement** [comment]
Ok so here is the solution:

```
var path = FileSystem.documentDirectory+"medias/"+this.selectedResource.id+".jpg"; //replace with yours
        const fromUri = await AssetUtils.fromUriAsync(path);
        fromUri.localUri = fromUri.uri;
        fromUri.downloaded = true;
        fromUri.uri = null;

        const asset = await AssetUtils.resolveAsync(fromUri);
   
        var img = new HTMLImageElement(fromUri);
        var tex = new PIXI.Texture.fromLoader(img);
        var background = PIXI.Sprite.from(tex);
  
        background.width = this.pixiRenderer.width;
        background.height = this.pixiRenderer.height;

        this.pixiStage.addChild(background);
        this.pixiRenderer._update();
```

**Comment by mlecoq** [comment]
Thanks for your help ! I have one problem left,

**Comment by mlecoq** [comment]
Ok found my mistake : my height value was calculated in order to fit image ratio, the obtained value was 426.6666667 so it was not taken into account (toFixed(2) fixed it)

**Comment by mlecoq** [comment]
Finally it does not work on Android (works fine on iOS), I have the following issue 

`[Unhandled promise rejection: Error: unexpected url: file:/data/user/0/host.exp.exponent/cache/ExperienceData/%2540archireport%252Farchireport-box/ImagePicker/d9905084-ec2c-4922-811e-b7da3aa6fa51.jpg]`


The picture has been taken just before editing it with Pixi (and can be displayed with this uri)

**Comment by DEllement** [comment]
it should be file:**///**data/user/0/host.exp.exponent/cache/ExperienceData/%2540archireport%252Farchireport-box/ImagePicker/d9905084-ec2c-4922-811e-b7da3aa6fa51.jpg

**Comment by mlecoq** [comment]
Ok I have replaced 'file:/' with 'file:///' 

The picture is now displayed but as soon as I draw on it, it disappears 😬

**Comment by DEllement** [comment]
ok I saw this problem, it also happened to me in the simulator which is honestly not as good as the real thing specs wise. Can you confirm me that it is in the simulator, can you try the same code on a real device?

**Comment by mlecoq** [comment]
Yes it is the simulator ! 🙌 I have no real device to test with it right now. I will try tomorrow with a real one 

Thanks again !!!

**Comment by DEllement** [comment]
Ok cool, I honestly dont know if the problem is a memory issue or a bug with the rendering itself, but on my end it work well even on older device, let us know your result it could be useful for others 

Thanks

**Comment by mlecoq** [comment]
Hi @DEllement , on a real device it works better but I have a strange issue. 

In fact I have 2 screens : first to take the picture and the second one to edit it

First screen to take the picture and display it:

![take the picture](https://s3.amazonaws.com/mle-sandbox/Screenshot_20190306-102652.png)

First edition (works fine)
![first edition](https://s3.amazonaws.com/mle-sandbox/Screenshot_20190306-102703.png)
![first edition saved](https://s3.amazonaws.com/mle-sandbox/Screenshot_20190306-102709.png)

Second edition (also fine)
![second edition](https://s3.amazonaws.com/mle-sandbox/Screenshot_20190306-102718.png)

Third edition : purple screen (Puuurppllle screeeeen 🎤)
![third edition](https://s3.amazonaws.com/mle-sandbox/Screenshot_20190306-102722.png)

and if I draw on it, white screen:
![white](https://s3.amazonaws.com/mle-sandbox/Screenshot_20190306-102730.png)

![black](https://s3.amazonaws.com/mle-sandbox/Screenshot_20190306-102735.png)

Then it crashes:
![crash 1](https://s3.amazonaws.com/mle-sandbox/Screenshot_20190306-102741.png)
![crash 2](https://s3.amazonaws.com/mle-sandbox/Screenshot_20190306-102747.png)

**Comment by mlecoq** [comment]
The issue appears sooner when I rotate the picture before saving it (using ImageManipulator.manipulateAsync from expo). After first edition, purple screen appears 🤔

**Comment by mlecoq** [comment]
Ok it is an issue related to navigation (react-navigation). When I use StackNavigation.reset it is fine. The only issue left is:


       const background = PIXI.Sprite.from(tex);

       background.width = this.sketchRef.renderer.width;

       background.height = this.sketchRef.renderer.height;


sometimes sketch.renderer is not defined

**Comment by mlecoq** [comment]
Hello @DEllement, it works fine. I had one left issue and it was my mistake : it did not use _onReady_ method to check if GL context is ready 

Thanks again !

**Comment by Ipicky22** [comment]
Hello,

I also want to make a drawing module on an image, with Expo Pixi, but I encounter the same problem.
I can not put my picture in the background.

Is it possible to give me a link to an entire sample code?
thank you

**Comment by DEllement** [comment]
Ok ill try to provide the bits that make it work on my end:

in your React Component
```
import * as ExpoPixi from 'expo-pixi';
...

onChangeAsync = async () => {
        const { uri } = await this.sketch.takeSnapshotAsync();
        this.vm.edititingImage = uri;
    };

<ExpoPixi.Sketch
                            ref={ref => (this.sketch = ref)}
                            style={{flex:1 }}
                            strokeColor={this.vm.hexStrokeColor}
                            strokeWidth={4}
                            strokeAlpha={1}
                            onReady={async context => {
                                this.vm.pixiRenderer = this.sketch.renderer;
                                this.vm.pixiStage = this.sketch.stage;
                            }}
                            onChange={this.onChangeAsync} />
```

in your ViewModel object or in the React Component itself if your logic is together:
```
import {FileSystem} from "expo";
import '@expo/browser-polyfill';
import { PIXI } from 'expo-pixi';
import AssetUtils from 'expo-asset-utils';

...
selectedResource:MediaResource
pixiRenderer:any;
pixiStage:any;
...

async loadResource():Promise<void>{
if (this.pixiStage.children.length > 0) {
                this.pixiStage.removeChildren();
                this.pixiRenderer._update(); 
            }

            var path = FileSystem.documentDirectory + "medias/" + this.selectedResource.id + ".jpg";

            const fromUri = await AssetUtils.fromUriAsync(path);
            fromUri.localUri = fromUri.uri;
            fromUri.downloaded = true;
            fromUri.uri = null;

            const asset = await AssetUtils.resolveAsync(fromUri); //Remove if not needed
            var img = new HTMLImageElement(fromUri);
            var tex = new PIXI.Texture.fromLoader(img);
            var background = PIXI.Sprite.from(tex);
            background.width = this.pixiRenderer.width;
            background.height = this.pixiRenderer.height;

            this.pixiStage.addChild(background);
            this.pixiRenderer._update();
}

...

Of course im not providing the entire codebase, but its simple enough to understand

**Comment by Ipicky22** [comment]
Hi @DEllement , I succeeded :)
I removed the lines on the PIXI.Texture and HTMLImageElement. It works without, if you have details of why it is better to use it for example, I'm interested.
At first I put everything in my component, so it's not very clean, I'll remake all that.

`
<ExpoPixi.Sketch
                        ref={ref => (this.sketch = ref)}
                        style={[styles.sketch, {
                            height: "100%",
                            width: "100%",
                        }]}
                        strokeColor={this.state.strokeColor}
                        onChange={this.onChangeAsync}
                        onReady={async context => {

                            const { uri } = this.state
                            const renderer = this.sketch.renderer
                            const stage = this.sketch.stage

                            if (stage.children.length > 0) {
                                stage.removeChildren()
                                renderer._update()
                            }

                            var background = await PIXI.Sprite.from(uri);

                            background.rotation = 1.5708
                            background.width = renderer.height
                            background.height = renderer.width
                            background.position.set(renderer.width, 0)

                            stage.addChild(background);
                            renderer._update();
                        }}
                        transparent={false}
                    />
`

Thank you again for your help

**Comment by DEllement** [comment]
The reason i ended doing that, its because it was at first working on iOS but not in android, i dont know if the problem was resolved since then. ill have a try . 

Thanks

**Comment by ClementWalter** [comment]
I come up with another solution: I have put my Sketch with transparent=True inside an ImageBackground component that holds the image:

```
    <View style={{flex: 1}}>
      <ImageBackground style={styles.background} source={{uri: this.state.photo.uri}}>
        <ExpoPixi.Sketch
             strokeColor="black"
             strokeWidth={10}
             strokeAlpha={1}
             transparent={true}
         />
      </ImageBackground>
    </View>;
```

**Comment by jesouhaite08** [comment]
I'm curious how you save this photo after drawing on it? I am trying to use takeSnapshotAsync, but it just produces a black image.

    const image = await takeSnapshotAsync(this.sketch, {
        quality: 1,
        format: 'jpg',
    });

**Comment by Dolla123** [comment]
Hello I need a help for 
`<ExpoPixi.FilterImage
            source={uri}
            resizeMode={'cover'}
            filters={filters}
            style={styles.image}
          />`

when I wrote source = {require('./asset/demo.png')} filters are working perfect, but when I add the pictures from Image picker or expo-camera it shows me 
`[Unhandled promise rejection: Error: Expected URL scheme 'http' or 'https' but was 'file']`

I am using windows 10 and android simulator and device, for both it is not working.

**Comment by kaushikparmar** [comment]
Hello Devs,

I could draw over the image but now I am getting two separate  images for two layers.
Plz guide me how to combine two layers or any other way.

**Comment by Shadowown** [comment]
<View style={{flex: 1}}>
      <ImageBackground style={styles.background} source={{uri: this.state.photo.uri}}>
        <ExpoPixi.Sketch
             strokeColor="black"
             strokeWidth={10}
             strokeAlpha={1}
             transparent={true}
         />
      </ImageBackground>
    </View>;
    
If you looking to save the image i combined this code and installed the package captureRef to save the view, Allowing you to draw on the image and save the image and the drawing as a whole.

**Comment by kaushikparmar** [comment]
Thanks, @Shadowown. It is useful.
