### ISSUE TITLE
FilterImage doesn't work with ImagePicker

### ISSUE THREAD

**Issue by maxusr** [expo/expo-pixi#7]
ExpoPixi.FilterImage don't work with localUri (file://) that's coming from Camera! I try with {uri} or direct with string link but none of both works! I have an error like

> "Could not find image file:///var/mobile/Containers/Data/Application/5DC0A462-A09B-4EB1-9CE9-CF12E53A93F5/Library/Caches/ExponentExperienceData/%2540anonymous%252Fapp-f6e1550f-8652-48a2-b465-3222938fc807/16D1E15D-6EEA-4E68-BAFD-0FD52DBC97E8.jpg"

**Comment by EvanBacon** [comment]
Could you share a snack please :)

**Comment by maxusr** [comment]
Hier is a Snack! Thanks

[https://snack.expo.io/SkAxgmyUz](Snack)

**Comment by CacaoRick** [comment]
Also happen when use `ExpoPixi.spriteAsync()`
localUri from `Expo.ImagePicker` result
(uri use in Image component is OK)

**Comment by EvanBacon** [comment]
This is a problem with expo-asset-utils: https://github.com/expo/expo-asset-utils/issues/1 will fix

**Comment by EvanBacon** [comment]
@maxusr @CacaoRick fixed: https://snack.expo.io/@bacon/expo-pixi-filterimage-cameraroll-example
