### ISSUE TITLE
TypeError: gl.createShader is not a function.

### ISSUE THREAD

**Issue by jeremytubbs** [expo/expo-pixi#82]
Hello, 

I am getting the following error when trying to run this example - https://github.com/expo/expo-pixi/blob/master/examples/filter-image/App.js when using `"expo": "^33.0.0"`

`TypeError: gl.createShader is not a function. (In 'gl.createShader(type)', 'gl.createShader' is undefined)`

Any help would be greatly appreciated. 

Thanks.

**Comment by afshawnlotfi** [comment]
Having the same issue. Get warning and nothing shows up

**Comment by duncan-iaria** [comment]
I believe this is an issue with the latest version of expo/browser-polyfill package that expo-pixi itself requires. The maintainer of both packages has just merged in a fix into that package. I'm not sure when this repo will be updated to use it, but you may want to downgrade to expo-pixi 1.0.1 until everything is updated.

If that doesn't work, try installing the gl-matrix package: https://www.npmjs.com/package/gl-matrix. The dependencies for expo-pixi are a bit wonky right now. If you are still have issues after those steps ... maybe I can be of further assistance?

**Comment by robksawyer** [comment]
I'm also running into issues here. I installed `expo-pixi` via `expo install expo-pixi@1.0.1`, hit the `expo-asset-utils` issue, so installed that as well (same way). Still didn't work, so I then installed `gl-matrix` via `expo install gl-matrix`. I still get the same error. Any other ideas?

**Comment by robksawyer** [comment]
> I believe this is an issue with the latest version of expo/browser-polyfill package that expo-pixi itself requires. The maintainer of both packages has just merged in a fix into that package. I'm not sure when this repo will be updated to use it, but you may want to downgrade to expo-pixi 1.0.1 until everything is updated.
> 
> If that doesn't work, try installing the gl-matrix package: https://www.npmjs.com/package/gl-matrix. The dependencies for expo-pixi are a bit wonky right now. If you are still have issues after those steps ... maybe I can be of further assistance?

Any other ideas?
