### ISSUE TITLE
Zoom in/out canvas image and sketch over it

### ISSUE THREAD

**Issue by jorgefernandes** [expo/expo-pixi#83]
Using expo-pixi a just figured out how to draw by canvas an Image on Sketch component and to sketch over it. But i want to know if i can have a little bit more control over the image, like decide when start to draw and when stop, and if i can zoom in/out pinching the canvas image and sketch

**Comment by anshgupta1234** [comment]
I have the same issue +1

**Comment by jorgefernandes** [comment]
he @anshgupta1234 i've wrapped my Sketch component into ImageZoom (react-native-image-pan-zoom) component. It worked :)
