### ISSUE TITLE
Expo SDK 33 - Sketch - undefined is not an object e.lastPoint.x

### ISSUE THREAD

**Issue by Xyzor** [expo/expo-pixi#87]
I upgraded from Expo SDK 32 to 33 and the expo-pixi module broke without any change from my part.

I've created a [demo](https://snack.expo.io/@fitsolutionskft/expo-pixi-sketch-test) to demonstrate my problem. When I try to draw something, the app dies with `undefined is not an object (evaluating 'e.lastPoint.x')`.

Do you guys have any idea about what's causing this or what am I doing wrong?

**Comment by zhangpao17** [comment]
try
"dependencies": {
     "@expo/browser-polyfill": "^0.0.1-alpha.3",
    "expo-asset-utils": "1.0.0",
    "expo-pixi": "1.0.1",
    "react-native-paper": "2.15.2"
  }

**Comment by Xyzor** [comment]
@zhangpao17 Did this work for you? The snack can't install expo-asset-utils module.

**Comment by zhangpao17** [comment]
@Xyzor  yes,  I use it in my app , it works fine ，maybe you can try [this](https://github.com/expo/expo-pixi/issues/77)

**Comment by Xyzor** [comment]
I mean did you manage to make the snack demo work with this?

**Comment by zhangpao17** [comment]
like this ?  ![image](https://user-images.githubusercontent.com/7531469/61509119-ab877480-aa1f-11e9-9a98-be3197bfa0d6.png)
