### ISSUE TITLE
Can't find variable asset

### ISSUE THREAD

**Issue by Makingweb** [expo/expo-pixi#9]
When ExpoPixi is imported, this error occurs

```import ExpoPixi from 'expo-pixi';```

![screenshot_1518893033](https://user-images.githubusercontent.com/2823810/36344473-174492e4-141b-11e8-8202-d0599474bcbe.png)

Do I forget something in packages.json?

package.json
```
    "EventEmitter": "^1.0.0",
    "expo": "^25.0.0",
    "expo-asset-utils": "^0.0.4-alpha.0",
    "expo-pixi": "^0.2.1",
    "frisbee": "^1.6.4",
    "path": "^0.12.7",
    "pixi-filters": "^2.5.1",
    "pixi.js": "^4.7.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-country-picker-modal": "^0.5.1",
    "react-native-elements": "^1.0.0-beta2",
    "react-native-form": "^2.1.2",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-mentions": "^1.1.4",
    "react-navigation": "^1.0.0-beta.27",
    "url": "^0.11.0"
```

**Comment by yehudahkay** [comment]
+1 getting same error

**Comment by jarvisluong** [comment]
Me too, I can't run any of the examples

**Comment by MobileAppVault** [comment]
Hi,

I've fixed the issue by fixing a typo in sprite.js.

from `export default asset;`
to `export default sprite;`

@expo: please correct this issue! :)

**Comment by EvanBacon** [comment]
😓 fixed sorry about that. Also adding lints to prevent this... It's moving from quick hack to actual lib now 😁
